version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQATestingForTokyo2609Project
  gitServerName: kusiTest2609
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqatestingfortokyo2609.integrations:Sum
  packages:
  - name: SIQATestingForTokyo2609Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2090
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2090
- serviceName: project.siqatestingfortokyo2609.integrations:deepclonetest
  packages:
  - name: SIQATestingForTokyo2609Project
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2090
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2090
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2090
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2090
