version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQATestingForTokyo2609Project
  gitServerName: kusiTest2609
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
